### ISSUE TITLE
Hi, would you please add how to use this in ktor project ?

### ISSUE THREAD

**Issue by ganeshmahajan1985** [papsign/Ktor-OpenAPI-Generator#1]
Hi this is nice, I am new to ktor.
would you please add how to use this in ktor project ?
like what to include in gradle.build file etc. step by step ?

**Comment by Wicpar** [comment]
Hi,
You can use it as submodule:

install the submodule:
```
git submodule add https://github.com/papsign/Ktor-OpenAPI-Generator.git openapigen
```

declare the folder in `settings.gradle`
```
...
include 'openapigen'
```

declare the dependency in the main `build.gradle`
```
dependencies {
    compile project(":openapigen")
    ...
}
```

**Comment by ganeshmahajan1985** [comment]
Hi @Wicpar ,
I tried this but on building the project it is giving error 
`Unresolved references:bind`
On like numbber 17 at OpenAPIGen.kt file
import javax.xml.**bind**.JAXBElement

**Comment by ganeshmahajan1985** [comment]
Hi @Wicpar ,

There are two changes i have made in build.gradle file and it is working for me now. 
1. Updated kotlin dependency using "apply plugin: 'kotlin'"
2. jvmTarget explicitly to 1.8 
```
tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}
```

It is woking as expected now.  Thanks

**Comment by Wicpar** [comment]
> Hi @Wicpar ,
> I tried this but on building the project it is giving error
> `Unresolved references:bind`
> On like numbber 17 at OpenAPIGen.kt file
> import javax.xml.**bind**.JAXBElement

the import was unused, i deleted it,
can you see if you still have to explicitly set the jvm version?
