### ISSUE TITLE
Why jcenter is required for implementation?

### ISSUE THREAD

**Issue by y9san9** [papsign/Ktor-OpenAPI-Generator#104]
This artifact located at `jcenter` while it is deprecated.
![image](https://user-images.githubusercontent.com/46930374/123106469-5214f500-d441-11eb-86a5-6f41f1cafcd7.png)

**Comment by Wicpar** [comment]
i believe it is fixed with the latest release

**Comment by y9san9** [comment]
Great job, thanks for your work 👍
