### ISSUE TITLE
Problem with authentication

### ISSUE THREAD

**Issue by RamsesGomez** [papsign/Ktor-OpenAPI-Generator#107]
We just recently changed from version 0.2-beta.14 to version 0.2-beta.18 and all the sudden the authentication method stop working.

We are using JWT Token to authenticate, now after updating the Authorization: Bearer is not added and when you click on the lock for the authenticated routes nothing shows in the authentication dialog.

![image](https://user-images.githubusercontent.com/69141757/126332160-16515446-27df-4941-9fec-198a8c0d8dd9.png)

Then we tested the different version and something changed from 14 to 15 that broke this for us. Do we need to change anything in the configuration. No error is being logged.

**Comment by Wicpar** [comment]
it's possible there was a regression

**Comment by RamsesGomez** [comment]
Any suggestion? An idea of what should we change?

**Comment by Wicpar** [comment]
do you have an implementation I can test to reproduce ?

**Comment by RamsesGomez** [comment]
when you said "It's possible there was a regression" what do you really mean by this? We are following the exact same example you have with the exception that we have both unauthorized routes and authorized ones. 
I Can see this in the log file: Value jwtAuth=[] is unknown
Maybe that helps. Unfortunately I do not have an implementation for you to test.

**Comment by Wicpar** [comment]
can you send the openapi.json ?
Have you tried the openapi.json on Redoc, it is has a better implementation of the standard.
A commit between *.14 and *.18 changed the definition as it was not coherent with the standard.
The regression would be in the library, as a few PRs have been accepted since.

**Comment by Wicpar** [comment]
@RamsesGomez I just tested the JWT test and it has the authorization as expected... I did update a few libraries though, let me wrap that up so you can try.

**Comment by Wicpar** [comment]
@RamsesGomez try the latest release and tell me if it works

**Comment by RamsesGomez** [comment]
@Wicpar Awesome let me try thanks a lot for the swift response

**Comment by RamsesGomez** [comment]
I tested it but no luck I can see that the new generated json looks like this:

`
"security": [
                    {
                        "entries": [
                            null
                        ],
                        "keys": [
                            "jwtAuth"
                        ],
                        "size": 1,
                        "values": [
                            [
                                "Dummy"
                            ]
                        ]
                    }
                ],
`

where as the old one looked like this:

`
"security": [
                    {
                        "jwtAuth": [
                            "Dummy"
                        ]
                    }
                ],
`

**Comment by RamsesGomez** [comment]
You mentioned you have an example that worked is it possible to see that sample?

**Comment by RamsesGomez** [comment]
Ok We found the problem... we have a custom serialization module to be able to use kotlin serialization, and the SecurityModel now is a Map and that was the problem, that all DataModel were being serialized differently but now is all good thanks a lot for the support much appreciated
