### ISSUE TITLE
Serializing collections of different element types is not yet supported

### ISSUE THREAD

**Issue by Methdogg** [papsign/Ktor-OpenAPI-Generator#120]
Why am i getting this error after launching swagger-ui?

ERROR Application - Unhandled: GET - /openapi.json
java.lang.IllegalStateException: Serializing collections of different element types is not yet supported. Selected serializers: [com.papsign.ktor.openapigen.model.schema.DataFormat, kotlin.Boolean, com.papsign.ktor.openapigen.model.schema.DataType]

**Comment by Wicpar** [comment]
can you get a more detailed stacktrace ?

**Comment by Methdogg** [comment]
It is not working with Gson. I changed to jackson for serialization then it works. You can close.

**Comment by Methdogg** [comment]
This error occurs when i use gson fyi.

**Comment by Wicpar** [comment]
Yes this library was made with Jackson in mind, glad it works now.
