### ISSUE TITLE
Models: `minimum: null/maximum: null` for `string` and `boolean` seem redundant

### ISSUE THREAD

**Issue by SerVB** [papsign/Ktor-OpenAPI-Generator#15]
In the models section, there are redundant fields:

![image](https://user-images.githubusercontent.com/20105593/76630756-9da7d600-6551-11ea-9e55-4c7c8b8a9b0a.png)

Current workaround is activating `mapper.setSerializationInclusion(Include.NON_NULL)` for Jackson.

However, it changes the way the server answers, so it's not a solution in some cases.

I think the solution can be just to omit generating `minimum` and `maximum` for `string` and `boolean` in the models section.

This is an issue extracted from #12.

**Comment by Wicpar** [comment]
made appropriate modifications in the rewoked-model branch.

`implementation 'com.github.papsign:Ktor-OpenAPI-Generator:reworked-model-SNAPSHOT'`

It will be merged into master when it is determined as clean and maintainable.

**Comment by SerVB** [comment]
Yep, this works! A small concern here that `.build()` is executed every time the request is performed. Maybe it's better to use a lazy property to store the built schema.

**Comment by Wicpar** [comment]
It is possible, in principle, to create new routes during runtime, so the model can in principle change. This is up to the user.
