### ISSUE TITLE
Missing @Example annotation

### ISSUE THREAD

**Issue by SerVB** [papsign/Ktor-OpenAPI-Generator#16]
In the models section, there is a field called "example". Currently it is equal to `null` for all fields in all classes:

![image](https://user-images.githubusercontent.com/20105593/76630777-a7313e00-6551-11ea-9222-1b9732de2c0b.png)

There should be a way to specify this field. Also, I think if the field is not specified, it shouldn't be presented in the models section.

This is an issue extracted from #12.

**Comment by Wicpar** [comment]
you can specify it per request like this: 
```kotlin
get<Unit, Response>(example = Response(...)) {

}

post<Unit, Response, Request>(
    exampleRequest = Request(...),
    exampleResponse = Response(...)
) { params, request ->

}
```

No  mechanism exists yet to provide examples per model globally.

**Comment by SerVB** [comment]
Yeah, I use examples for methods. I'm not an experienced user of OpenAPI, so I don't know if examples of fields are also usually defined...

If yes, I want an opportunity to define them.

If no, just remove these "example" fields.

**Comment by Wicpar** [comment]
i will add such a mechanism as it is part of the standard.
until then you can use the new branch with the reworked models. null fields are now filtered when you use `OpenAPIModel.build()`
it will generate the appropriate hashmaps and remove empty and null values

**Comment by Wicpar** [comment]
Added `@WithExample` in the latest commit.
SwagerUI doesn't handle it properly anyway.
```kotlin
        @WithExample
        class C(val l: @Clamp(0, 10) Long) : Base() {
            companion object: ExampleProvider<C> {
                override val example: C? = C(5)
            }
        }
```
or
```kotlin
        @WithExample(CExampleProvider::class)
        class C(val l: @Clamp(0, 10) Long) : Base()
...
        object CExampleProvider: ExampleProvider<C> {
                override val example: C? = C(5)
        }
```

**Comment by Wicpar** [comment]
`implementation 'com.github.papsign:Ktor-OpenAPI-Generator:0.2-beta.0-experimental'`
