### ISSUE TITLE
Feature: allow to name namespace

### ISSUE THREAD

**Issue by SerVB** [papsign/Ktor-OpenAPI-Generator#18]
Namespace can have a name and a description (for example, `api - Default namespace`):

![image](https://user-images.githubusercontent.com/20105593/76679291-6a685400-65f0-11ea-8381-c8b5047a01a4.png)

However, in `Ktor-OpenAPI-Generator`, I have only `default` and I have no idea if this is possible to change now:

![image](https://user-images.githubusercontent.com/20105593/76679320-a26f9700-65f0-11ea-824c-9480d4dff818.png)

**Comment by Wicpar** [comment]
Tags are what you are looking for.
There is an example here: https://github.com/papsign/Ktor-OpenAPI-Generator/blob/master/src/test/kotlin/TestServer.kt
