### ISSUE TITLE
Status code in "throws" block variant

### ISSUE THREAD

**Issue by SerVB** [papsign/Ktor-OpenAPI-Generator#22]
Hi! I have the following code:

![image](https://user-images.githubusercontent.com/20105593/77701313-09b12200-6fc7-11ea-9919-d5ef419243d9.png)

As you see, status code is duplicated. So I don't understand which has a higher priority...

Can I omit this duplication?

**Comment by Wicpar** [comment]
`@Response` is only used with the response `get<Param, Response> {}` of the request, not the exception.
