### ISSUE TITLE
Description for throws block

### ISSUE THREAD

**Issue by SerVB** [papsign/Ktor-OpenAPI-Generator#24]
Hi! Is it currently possible to add description text? By default, a status is the description.

![image](https://user-images.githubusercontent.com/20105593/77798524-19db0700-7084-11ea-8d57-e29bb6575f6b.png)

**Comment by Wicpar** [comment]
Until i can find something more elegant you can use `HttpStatusCode(400, "The description you want")`

**Comment by SerVB** [comment]
Great, thank you, it works!
