### ISSUE TITLE
Multipart Example

### ISSUE THREAD

**Issue by mintu19** [papsign/Ktor-OpenAPI-Generator#33]
I am trying to create route to receive upload file to server but not able to find a way to implement it. I have seen multipart content provider in code but not sure how to use it.

How to write post data server code for multipart something like this:
https://ktor.io/servers/uploads.html

**Comment by Wicpar** [comment]
Hi, It is natively supported by the library, example:
```kotlin
@FormDataRequest
data class PDFFileCreateDTO(@PartEncoding("application/pdf") val file: NamedFileInputStream, val name: String, val public: Boolean)
```
It has not been tested yet on the experimental branch, but it should work, if it doesn't please create an issue.
