### ISSUE TITLE
incorrect 'throws' rendering

### ISSUE THREAD

**Issue by y9san9** [papsign/Ktor-OpenAPI-Generator#45]
`
throws(APIException.apiException<ApiError, String>(HttpStatusCode.BadRequest, ""), fn = fn)
`
This code have that result for me 
![image](https://user-images.githubusercontent.com/46930374/81987287-fd9a2600-9641-11ea-9427-d6095e44e33d.png)

**Comment by y9san9** [comment]
I have tried same with KotlinNullPointerException but not with my custom one. The result is same, logs here 
![image](https://user-images.githubusercontent.com/46930374/81987571-916bf200-9642-11ea-8efe-039102567451.png)

**Comment by Wicpar** [comment]
can you try the new syntax ?
https://github.com/papsign/Ktor-OpenAPI-Generator/wiki/A-few-examples#exceptions-and-multiple-responses

**Comment by Wicpar** [comment]
Also, swagger-ui does not cover the full OpenAPI spec, i need to see the openapi.json for that request to verify what is going wrong.

**Comment by Wicpar** [comment]
Another issue could be that your gradle cache has an older version of snapshot, try to upgrade to a release version

**Comment by y9san9** [comment]
I have found the reason. There was another throws {} block in upper level. If sumplify 
`throws(...){
    throws(...){}
}`
I expected to catch exceptions by upper block for all requests, then jsonify and respond with it, but show error specifications in lover block for every single request
UPD: Just now have same error by using vararg APIException

**Comment by Wicpar** [comment]
can you provide a code sample ?

**Comment by y9san9** [comment]
Sure, I've simplified it with null pointer
`throws(
        apiException<KotlinNullPointerException, String>(HttpStatusCode.BadRequest, "test"),
        apiException<KotlinNullPointerException, String>(HttpStatusCode.BadRequest, "test"),
        fn = fn
    )`

**Comment by y9san9** [comment]
That's it
![image](https://user-images.githubusercontent.com/46930374/81992910-40adc680-964d-11ea-9400-b8bd54c1a8c8.png)

**Comment by y9san9** [comment]
You should use another json code (and also I think that required ability to change example names)
![image](https://user-images.githubusercontent.com/46930374/81993812-2f65b980-964f-11ea-9398-c2c510b7b66b.png)

**Comment by Wicpar** [comment]
Ah i see, i'll look into it.

**Comment by Wicpar** [comment]
fixed in 0.2-beta.4
For more accurate names and descriptions there is no quick fix, this whole part needs a rework... #48
