### ISSUE TITLE
create tag with name and description

### ISSUE THREAD

**Issue by y9san9** [papsign/Ktor-OpenAPI-Generator#46]
`inline fun NormalOpenAPIRoute.tag(name: String = "", description: String = "", crossinline fn: NormalOpenAPIRoute.() -> Unit) {
    tag(object : APITag {
        override val description = description
        override val name = name
    }, fn)
}`
Sorry now I have a little bit time to create PM. You can add this code to create tags with name and description instead of implementing interface (or write if this functionality already exists)

**Comment by Wicpar** [comment]
There is already a tag functionality, i has to be an enum though.
You can see it implemented here:
https://github.com/papsign/Ktor-OpenAPI-Generator/blob/master/src/test/kotlin/TestServer.kt

**Comment by y9san9** [comment]
Thanks I have checked first reply and now I've reworked my tags with enums. That's better and it's not important to implement my way of creating tags
