### ISSUE TITLE
Header without backtits

### ISSUE THREAD

**Issue by y9san9** [papsign/Ktor-OpenAPI-Generator#50]
I want to create header without '-', but if I create @HeaderParam with name Authorization, this header will not appear in request as there
![image](https://user-images.githubusercontent.com/46930374/82120375-38a97000-978e-11ea-8969-186d7b312990.png)

**Comment by onroundit** [comment]
same :(

**Comment by y9san9** [comment]
If I use '-' then there is no bug
![image](https://user-images.githubusercontent.com/46930374/82120409-7ad2b180-978e-11ea-90a8-31c21f579f17.png)

**Comment by Wicpar** [comment]
alright, i'll get something done

**Comment by Wicpar** [comment]
the latest snapshot has @OpenAPIName
```kotlin
    data class NameParam(@HeaderParam("A simple Header Param") @OpenAPIName("X-NAME") val name: String)
```
I tested it with parameters only, i don't know if it can be used on with request and response types.

**Comment by y9san9** [comment]
Thanks, that works pretty well, but still variable with name without backtits and annotation does not puts into request by swagger. For me now it's not problem, but for someone can be
Also I will check @OpenAPIName on requests&responses and will open issue if something will be wrong

**Comment by y9san9** [comment]
Sorry for mis info, I discrovered that this bug appears only with 'Authorization' header and that's cuz I should use Authorization with your library, can you give me some links ?

**Comment by Wicpar** [comment]
Alright, closing then.
For auth look at #8, it applies to all authentication schemes
