### ISSUE TITLE
use parameter not once

### ISSUE THREAD

**Issue by y9san9** [papsign/Ktor-OpenAPI-Generator#51]
![image](https://user-images.githubusercontent.com/46930374/82132526-450ee680-97e9-11ea-9338-8a6ef3116672.png)
I have this models and I am using auth param in almost every request (there can be other parameter, not only auth). Can I somehow create data class with this param and then use it in other classes. My vision of it is in screenshot

**Comment by y9san9** [comment]
I'm copy & pasting same parameters every time and it makes my code worse

**Comment by Wicpar** [comment]
Right now there is no way around it, if kotlin had vararg templates it would be fine, but the best shot at solving this is #10 and it would be quite a big change for the library.

**Comment by Wicpar** [comment]
Also if you use authentication you should rather use authenticated routes and the auth provider, it allows you to share logic on the endpoints to get the authenticated principal object directly

**Comment by y9san9** [comment]
Okey, thanks for your reply. Waiting for #10

**Comment by y9san9** [comment]
I have suggestion how to implement this
`route<GetTasksParams>("/tasks"){ params ->
            route<AuthParams>("/auth"){ otherParams ->
                get<AnotherParams, ...> { anotherParams ->

                }
            }
            post<SomeOtherParams, ...> { someOtherParams ->
                
            }
        }
`
I dont know about possibility to do this, but this syntax would be nice

**Comment by Wicpar** [comment]
that is not possible directly, sadly, but something like this would be possible
```kotlin
route<GetTasksParams>("/tasks"){ params ->
    route<AuthParams>("/auth"){ otherParams ->
       get<AnotherParams, ...> { anotherParams ->
           val paramsInstance = this.getParams(params) // needs to be resolved explicitly
           val otherParamsInstance = this.getParams(otherParams)
       }
    }
}
```

**Comment by y9san9** [comment]
Oke, I understand. Can you implement this ?

**Comment by Wicpar** [comment]
not any time soon sadly, i'm quite busy at the moment and can only spare an hour here an there...
If you think you can implement it feel free to open a pull request.

**Comment by y9san9** [comment]
Okey, I will think more about it later and if I find better solution I'll implement it
