### ISSUE TITLE
Multiple responses

### ISSUE THREAD

**Issue by Globegitter** [papsign/Ktor-OpenAPI-Generator#6]
Another thing I just ran into and I am not sure on how to specify, what if my endpoint has different types it can return and multiple response codes?

Top be precise for that endpoint we return `data class ErrorResponse(val message: String)` in cases where we return a 400, 404 and 500 status but not sure how I can define that.

Further when we may return a 201 with en empty response. How can this all be defined? It is not quite clear to me from the existing examples.

**Comment by Wicpar** [comment]
use the throws route selector:

```kotlin

                throws(APIException.apiException(HttpStatusCode.BadRequest) {it: Exception -> 
                    ExceptionDescriptionDTO(it)
                }) {
                    ...
                }

```

**Comment by Globegitter** [comment]
Ah cool, thanks for the examples. The first thing that came to my mind and I tried was again using sealed classes so e.g. having 

```
sealed class MyResponses

@Response("An NotFound error response", 404)
data class NotFoundResponse(val message: String): MyResponses()

@Response("Response when request was a success", 201)
object Created: MyResponses()
```

but this has some drawbacks in itself and what you just posted is more than sufficient for now thanks.

**Comment by Wicpar** [comment]
@Request and @Response only work on the reified type you declare, subclasses are not analyzed, and at runtime no reflection occurs.

**Comment by Globegitter** [comment]
@Wicpar One more question - how can I provide example for the error responses in the `StatusPages` integration?

**Comment by JavierPAYTEF** [comment]
Hey I'm currently writting the docs and changing the names but I'm going crazy with a problem I can't find the reason for. The body and response for all my services are empty.
I managed to track it to RequestHandlerModule when it does `provider.ofType<BodyParser>()` it always returns null.
I'm not sure why the BodyParser module is empty. Do I need to register the BodyParser myself someway?

This is an example of the data clases not appearing:

```kotlin
data class PinPadStatusReq(
    var language: String = "es", // es
    var pinpad: String = "*" // *
)

data class PinPadStatusResp(
    var datacenterMessage: String = "Conexión estable",
    var datacenterPingMS: Int = 140,
    var pinpads: List<Pinpad> = listOf(Pinpad())
) {
    data class Pinpad(
        var default: Boolean = true,
        var serialNumber: String = "123456789",
        var status: String = "#connected"
    )
}
```
This is my configuration:

```kotlin
val api = install(OpenAPIGen) {
	oaConfig.installIn(this)
}
install(ContentNegotiation) {
	/*jackson {
		setSerializationInclusion(JsonInclude.Include.NON_NULL)
		enable(SerializationFeature.INDENT_OUTPUT) // Pretty Prints the JSON
	}*/
	jackson {
		enable(
			DeserializationFeature.WRAP_EXCEPTIONS,
			DeserializationFeature.USE_BIG_INTEGER_FOR_INTS,
			DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS
		)

		enable(SerializationFeature.WRAP_EXCEPTIONS, SerializationFeature.INDENT_OUTPUT)

		setSerializationInclusion(JsonInclude.Include.NON_NULL)

		setDefaultPrettyPrinter(DefaultPrettyPrinter().apply {
			indentArraysWith(DefaultPrettyPrinter.FixedSpaceIndenter.instance)
			indentObjectsWith(DefaultIndenter("  ", "\n"))
		})

		//registerModule(JavaTimeModule())
	}
}
install(CallLogging) {
	level = Level.DEBUG
}
install(StatusPages) {
	withAPI(api) {
		exception<Exception, ErrorResponse>(HttpStatusCode.InternalServerError) { exception ->
			ResponseBuilder.error(exception)
		}
		status(HttpStatusCode.NotFound) {
			call.respond(
				HttpStatusCode.NotFound,
				ResponseBuilder.error("notFound", "Requested page was not found")
			)
		}
	}
}
routing{
	get("/openapi.json") {
		call.respond(application.openAPIGen.api.serialize())
	}
	get("/swagger") {
		call.respondRedirect("/swagger-ui/index.html?url=/openapi.json", true)
	}
}
apiRouting {
	route("/pinpad/status") {
		post<Unit, PinPadStatusResp, PinPadStatusReq>(
			info("PIN/PAD status"),
			exampleResponse = PinPadStatusResp(),
			exampleRequest = PinPadStatusReq()
		) { _, body ->
			respond(PinPadStatusResp())
		}
	}
}
```

This is what the json looks like:
![json](https://user-images.githubusercontent.com/40425968/86196343-6f163100-bb29-11ea-901a-20029be5eb9b.png)
