### ISSUE TITLE
jitpack build broken

### ISSUE THREAD

**Issue by Globegitter** [papsign/Ktor-OpenAPI-Generator#7]
Sorry for opening one issue after another and thanks for being so quick to respond, but here is one more. As I am not always a fan of using git submodules I thought I would give jitpack a try since that has worked for me quite well so far, but for some reason the build for this project is broken, see: https://jitpack.io/#papsign/Ktor-OpenAPI-Generator/c2b7932414 and https://jitpack.io/com/github/papsign/Ktor-OpenAPI-Generator/c2b7932414/build.log

Not sure if it would be a lot of effort to get this building on jitpack but it could be nice to give people an alternative to using git submodules.

**Comment by Wicpar** [comment]
I wanted to add it to jitpack anyway eventually, so it's done now.
