### ISSUE TITLE
Using Ktor locations

### ISSUE THREAD

**Issue by JanStoltman** [papsign/Ktor-OpenAPI-Generator#70]
Hey, is it possible to use this library in conjunction with Ktor's Locations mechanism? I've taken look at the examples but I still cannot figure it out

**Comment by Wicpar** [comment]
You can, but any paths defined with Ktor Locations won't be documented in the openapi spec.

**Comment by JanStoltman** [comment]
Cool, thank you for info!

**Comment by Marek00Malik** [comment]
what do you mean they won't be documented?
How should we add them?
