### ISSUE TITLE
NPE when missing required field on header

### ISSUE THREAD

**Issue by inaiat** [papsign/Ktor-OpenAPI-Generator#74]
Example:
```
http -v :8080/header 
GET /header HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:8080
User-Agent: HTTPie/2.2.0



HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Content-Length: 0
```

Returns this exception on server: **java.lang.reflect.InvocationTargetException: null**

So, this exception is much generic to handler with throws DSL.

I think the one option is a specific exception for this case

Thank you.

**Comment by Wicpar** [comment]
released and fixed
