### ISSUE TITLE
add primitive converter factory for kotlin.Byte

### ISSUE THREAD

**Issue by y9san9** [papsign/Ktor-OpenAPI-Generator#76]
![image](https://user-images.githubusercontent.com/46930374/93119500-901f0480-f6ca-11ea-9711-01a4fbf5598b.png)

**Comment by Wicpar** [comment]
Yes, bytes have not been added to the primitives. You can use an Int and `@Min(-128)` `@Max(127)`

**Comment by Wicpar** [comment]
added in latest commit

**Comment by y9san9** [comment]
Thank you, good job!
