### ISSUE TITLE
SecurityModel not serialized properly.

### ISSUE THREAD

**Issue by leeaaron629** [papsign/Ktor-OpenAPI-Generator#79]
Hi

I've gotten the JWTAuth working, but it doesn't work with the generated Swagger. This is how it's currently being generated:

```json
{ "security": [ {} ] }
```

 If, I modified the Swagger by adding: 
```json
{
  "security": [
    {
      "apiV1": [
        "abc"
      ]
    }
  ]
}
```

It works!

Also, it's generating an extra "name" field that Swagger Editor does not like.

```json
{
  "securitySchemes": {
    "apiV1": {
      "bearerFormat": "JWT",
      "scheme": "bearer",
      "type": "http",
      "name": "apiV1"
    }
  }
}
```

I've made a PR to demonstrate the problem: https://github.com/papsign/Ktor-OpenAPI-Generator/pull/78

Here's the full JSON object for the path:
```json
{"/v1":{"get":{"parameters":[{"allowEmptyValue":false,"deprecated":false,"description":"dummy query param","explode":false,"in":"query","name":"dummyQueryParam","required":false,"schema":{"nullable":false,"type":"string"},"style":"form"}],"responses":{"200":{"content":{"application/json":{"example":"OK","schema":{"nullable":false,"type":"string"}}},"description":"OK"}},"security":[{"apiV1":["abc"]},{"apiV2":[]}],"summary":"Health Check Endpoint"}}}
```

**Comment by Onlyhope** [comment]
I took a deeper look at this and realize it doesn't serialize empty lists within the map. Is that intended?

**Comment by Wicpar** [comment]
The name parameter is a known issue, i'll look into it when i have some time. If you can fix it i'll accept the PR.
