### ISSUE TITLE
Example Project

### ISSUE THREAD

**Issue by juliocesarsantos1020** [papsign/Ktor-OpenAPI-Generator#80]
Do you have a project where I can better understand how to use this library?

**Comment by SimonBrodtmann** [comment]
I guess it would suffice if the examples weren't so minimalistic. Just add a complete example here and there. Not just one line.
One thing I'm currently struggling with:
```
route("{str}") {
    get<StringParam, ResponseType> { params ->  // get request on '/{str}', str will be the string 
        respond(ResponseType(...))
    }
}
```
No context around it and, most important, "ResponseType(...)". Common. Make it a real example. Tell me how you access the value of "str". As someone new to Kotlin it's a real struggle with such minimalistic examples.

Besides that, I want to say thank you for this library. I'm very happy with the things that I already got to work.

**Comment by Wicpar** [comment]
I don't really soo how to make it more explicit, making documentation is not my strong suit, String param is the param object, here with a simple string, populated from the request parameters. The response type is the type that is serialized when you send a response with the respond function.

**Comment by Wicpar** [comment]
@juliocesarsantos1020 see the test folder, you have multiple files with a full example, some more complex than the other

**Comment by SerVB** [comment]
@juliocesarsantos1020 , you can check my project out: https://github.com/SerVB/e-shop

@Wicpar , maybe it's worth adding something like "showcase" section to the README, to link projects that use Ktor-OpenAPI-Generator?

**Comment by Wicpar** [comment]
@SerVB sure, you can do a PR for that section at the bottom of the readme.
