### ISSUE TITLE
FormDataRequest issue with nullable parameters

### ISSUE THREAD

**Issue by BernatCarbo** [papsign/Ktor-OpenAPI-Generator#83]
Hi there, I'm having a little issue with a FormDataRequest post request, I'm using the next request body:
![testRequest](https://user-images.githubusercontent.com/41543253/101405447-6431aa80-38d8-11eb-92c9-227fee9cc738.png)

This is translated as:
![requestBody](https://user-images.githubusercontent.com/41543253/101406177-66483900-38d9-11eb-9991-bc3713fb431c.png)
![testRequest2](https://user-images.githubusercontent.com/41543253/101406186-6811fc80-38d9-11eb-86cf-b4abf2d68ef7.png)

But all the parameters are added to the request (even the ones which are not specified) at this way:
```
"Content-Type: multipart/form-data" -F "abbreviation= " -F "name= " -F "icon= "
````
I believe that those shouldn't be added to the request if aren't specified

**Comment by Wicpar** [comment]
You mean in the swagger UI interface ?
This is expected behavior as there is no way to separate empty strings from null, since the field is always displayed.

**Comment by BernatCarbo** [comment]
Hello,
Yes, from the swagger UI, when I click at 'execute' I would expect to be sent only the paramaters that have been specified with values (and hence the rest are null), for example from this (only the name field have a value, the rest are null): 
![101406177-66483900-38d9-11eb-9991-bc3713fb431c](https://user-images.githubusercontent.com/41543253/101619469-9eec2d80-3a13-11eb-9364-8fd72c09843e.png)
I would expect the parameter 'name' to be sent at the request, but not the rest of them which doesn't have any value specified.

**Comment by Wicpar** [comment]
I do not manage the swagger UI project so I cannot help you with that, you can find another ui that accepts OpenAPI.json that suits your needs and disable the swagger ui in the settings.
