### ISSUE TITLE
Http headers should not be case sensitive

### ISSUE THREAD

**Issue by sigmanil** [papsign/Ktor-OpenAPI-Generator#96]
Http headers received using the HeaderParam-anotation are interpreted in a case sensitive manner. This goes against the definition of such headers, which says they are case-**in**sensitive. (https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2)

**Comment by Wicpar** [comment]
indeed, i have no time in the short term to do it but if anyone is up to do a PR i'll take it.

**Comment by sigmanil** [comment]
@Wicpar  Made an attempt to fix this in the above pull request. I'm not sure I did it the best way possible (to be honest those "builders" almost defeated me), but tests seem to indicate it works at least. Maybe this gets us a bit closer?

**Comment by Wicpar** [comment]
The builders also almost defeated me, the openapi spec for the more advanced query formats is pure pain but i was happy once it was working. 
You unfortunately overshot a bit the scope of the issue by making query params case insensitive as well...

**Comment by Wicpar** [comment]
Release has been pushed.
The fix was very simple after all, feel free to look at the commit: 46acb38
Sorry that you lost time on this.

**Comment by sigmanil** [comment]
@Wicpar As long as it's been fixed, I'm happy! :-) Thank you!
