### ISSUE TITLE
Swagger-Ui sorted alphabetically

### ISSUE THREAD

**Issue by vitormbgoncalves** [papsign/Ktor-OpenAPI-Generator#99]
My schemas in swagger-ui by default are sorted alphabetically. Is there a way for this not to be sorted alphabetically, and to be shown as in class order?

![Screenshot_20210525_120346](https://user-images.githubusercontent.com/51725817/119521884-eb24f300-bd51-11eb-90b6-4715e99350c4.png)

**Comment by Wicpar** [comment]
The structures used are maps, and thus sort the elements automatically.
If you wish you can do a PR to implement an alternative.
